export interface Amenity {
    label: string;
    icon: string;
}

export const AMENITIES: { [propertyType: string]: Amenity[] } = {
    'Common': [
        { label: 'Entrance Gate', icon: 'fa-door-open' },
        { label: 'Outer Boundaries', icon: 'fa-border-all' },
        { label: 'Underground Electrification', icon: 'fa-bolt' },
        { label: 'Street Light Poles', icon: 'fa-lightbulb' },
        { label: 'Plot Demarcation', icon: 'fa-map-marked-alt' },
        { label: 'Street Demarcation', icon: 'fa-road' },
        { label: 'Temple', icon: 'fa-place-of-worship' },
        { label: 'Plot Boundaries', icon: 'fa-vector-square' },
        { label: 'Beautiful Plantation', icon: 'fa-tree' },
        { label: 'Kids Play Area', icon: 'fa-child' },
        { label: 'Open Gym Area', icon: 'fa-dumbbell' },
        { label: 'Yoga Area', icon: 'fa-spa' },
        { label: 'Badminton Court', icon: 'fa-table-tennis' },
        { label: 'Irrigation System', icon: 'fa-tint' },
        { label: 'Open Theatre', icon: 'fa-film' },
        { label: 'Road Tiles', icon: 'fa-grip-horizontal' },
        { label: 'Garbage Collector', icon: 'fa-trash' },
        { label: '24x7 Security', icon: 'fa-shield-alt' },
        { label: 'Community Hall', icon: 'fa-users' },
        { label: 'Water Tank', icon: 'fa-water' },
        { label: 'Underground Sewage Line', icon: 'fa-stream' },
        { label: 'Jogging Track', icon: 'fa-running' },
        { label: 'Roadside Plantation', icon: 'fa-seedling' },
        { label: 'Park Pathways', icon: 'fa-walking' },
        { label: 'Wide Roads', icon: 'fa-road' },
        { label: 'EV Charging Stations', icon: 'fa-charging-station' },
    ],
    'Villa': [
        { label: 'Swimming Pool', icon: 'fa-swimming-pool' },
        { label: 'Banquet Hall', icon: 'fa-glass-cheers' },
        { label: 'Club House', icon: 'fa-building' },
        { label: 'Restaurant', icon: 'fa-utensils' },
        { label: 'Gymnasium', icon: 'fa-dumbbell' },
        { label: 'Retail Shopping', icon: 'fa-shopping-bag' },
        { label: 'Landscape Park', icon: 'fa-leaf' },
        { label: 'Private Garden', icon: 'fa-seedling' },
        { label: 'Home Automation', icon: 'fa-home' },
        { label: 'Private Parking', icon: 'fa-parking' },
        { label: 'Servant Quarter', icon: 'fa-house-user' },
        { label: 'Terrace', icon: 'fa-layer-group' },
        { label: 'Solar Panels', icon: 'fa-solar-panel' },
        { label: 'CCTV Surveillance', icon: 'fa-video' },
        { label: 'Intercom System', icon: 'fa-phone' },
        { label: 'Rain Water Harvesting', icon: 'fa-cloud-rain' },
        { label: 'Fire Safety System', icon: 'fa-fire-extinguisher' },
        { label: 'Jacuzzi', icon: 'fa-hot-tub' },
        { label: 'Home Theatre Room', icon: 'fa-tv' },
        { label: 'Private Lift', icon: 'fa-sort' },
    ],
    'Plots Township': [
        { label: 'Corner Plots Available', icon: 'fa-compress-arrows-alt' },
        { label: 'Vastu Compliant Plots', icon: 'fa-compass' },
        { label: 'Ready for Construction', icon: 'fa-hard-hat' },
        { label: 'Gated Township', icon: 'fa-shield-alt' },
        { label: 'Underground Water Pipeline', icon: 'fa-water' },
        { label: 'Electricity Connection Ready', icon: 'fa-plug' },
        { label: 'Street Numbering', icon: 'fa-hashtag' },
        { label: 'Drainage System', icon: 'fa-stream' },
        { label: 'CC Road Internal', icon: 'fa-road' },
        { label: 'Streetside Trees', icon: 'fa-tree' },
        { label: 'Plot Registry Ready', icon: 'fa-file-contract' },
    ],
    'Modern Apartment': [
        { label: 'Lift', icon: 'fa-sort' },
        { label: 'Power Backup', icon: 'fa-car-battery' },
        { label: 'Covered Parking', icon: 'fa-parking' },
        { label: 'Visitor Parking', icon: 'fa-parking' },
        { label: 'Rooftop Garden', icon: 'fa-seedling' },
        { label: 'Co-working Space', icon: 'fa-laptop' },
        { label: 'Laundry Room', icon: 'fa-tshirt' },
        { label: 'Package Locker Room', icon: 'fa-box' },
        { label: 'Pet Zone', icon: 'fa-paw' },
        { label: 'Concierge Service', icon: 'fa-concierge-bell' },
        { label: 'CCTV All Floors', icon: 'fa-video' },
        { label: 'Video Door Phone', icon: 'fa-phone-alt' },
        { label: 'Fire Sprinkler System', icon: 'fa-fire-extinguisher' },
        { label: 'Modular Kitchen', icon: 'fa-utensils' },
        { label: 'Piped Gas', icon: 'fa-fire' },
        { label: 'High Speed Internet', icon: 'fa-wifi' },
        { label: 'Swimming Pool', icon: 'fa-swimming-pool' },
        { label: 'Gymnasium', icon: 'fa-dumbbell' },
        { label: 'Multipurpose Hall', icon: 'fa-users' },
    ],
    'Farm House': [
        { label: 'Private Farm Land', icon: 'fa-tractor' },
        { label: 'Orchard Garden Area', icon: 'fa-apple-alt' },
        { label: 'Bore Well', icon: 'fa-water' },
        { label: 'Open Air Dining', icon: 'fa-campground' },
        { label: 'Bonfire Area', icon: 'fa-fire' },
        { label: 'Organic Farming Area', icon: 'fa-seedling' },
        { label: 'Animal Shed', icon: 'fa-horse' },
        { label: 'Caretaker Quarter', icon: 'fa-house-user' },
        { label: 'Private Swimming Pool', icon: 'fa-swimming-pool' },
        { label: 'Outdoor BBQ Area', icon: 'fa-fire-alt' },
        { label: 'Nature Trails', icon: 'fa-hiking' },
        { label: 'Bird Watching Area', icon: 'fa-dove' },
        { label: 'Solar Power System', icon: 'fa-solar-panel' },
        { label: 'Rainwater Harvesting Tank', icon: 'fa-cloud-rain' },
        { label: 'Boundary Wall', icon: 'fa-border-all' },
        { label: 'Private Gate', icon: 'fa-door-open' },
        { label: 'Barn Storage Area', icon: 'fa-warehouse' },
    ],
};